# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bebrandt <benoit.brandt@proton.me>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/05 13:13:50 by bebrandt          #+#    #+#              #
#    Updated: 2024/11/05 15:15:42 by bebrandt         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MAKEFLAGS		=	--no-print-directory
EX_00_NAME		=	megaphone
TEST_EX_00_NAME	=	test_megaphone

BUILD_DIR		=	../mk_build/

MAKE_EX00		= $(BUILD_DIR)makefile_ex00.mk
MAKE_EX01		= $(BUILD_DIR)makefile_ex01.mk
MAKE_EX02		= $(BUILD_DIR)makefile_ex02.mk

-include $(MAKE_EX00)
-include $(MAKE_EX01)
-include $(MAKE_EX02)
