# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bebrandt <benoit.brandt@proton.me>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/05 13:13:50 by bebrandt          #+#    #+#              #
#    Updated: 2024/11/05 14:21:08 by bebrandt         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MAKEFLAGS	=	--no-print-directory

BUILD_DIR	=	build/

MAKE_EX00	= $(BUILD_DIR)makefile_ex00.mk
MAKE_EX01	= $(BUILD_DIR)makefile_ex01.mk
MAKE_EX02	= $(BUILD_DIR)makefile_ex02.mk

-include $(MAKE_EX00)
-include $(MAKE_EX01)
-include $(MAKE_EX02)
